export interface GalleryItem { id: number; title: string; category: 'dssr' | 'paix' | 'leadership'; categoryLabel: string; section: string; img: string; desc: string; date: string; tag: string; }

export const galleryItems: GalleryItem[] = [
  // PROJECT 1: DSSR et VBG (3 ACTIONS)
  
  // Action 1: Atelier TEDIJO3
  {
    "id": 20,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 1",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0090.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 1/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 21,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 2",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0070.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 2/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 22,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 3",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0059.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 3/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 23,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 4",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0060.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 4/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 24,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 5",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0066.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 5/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 25,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 6",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0073.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 6/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 26,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 7",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0077.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 7/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 27,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 8",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0081.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 8/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 28,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 9",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0083.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 9/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 29,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 10",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0090_zrbKHfy.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 10/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 30,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 11",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0094.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 11/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 31,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 12",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0098.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 12/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 32,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 13",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0102.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 13/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 33,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 14",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251016-WA0103.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 14/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 34,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 15",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251017-WA0103.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 15/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 35,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 16",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251017-WA0104.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 16/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 36,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 17",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251017-WA0105.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 17/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 37,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 18",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251017-WA0106.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 18/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },
  {
    "id": 38,
    "title": "Atelier de lancement du projet TEDIJO3 - Vue 19",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG-20251017-WA0108.webp",
    "desc": "Photo prise lors de l'activité: Atelier de lancement du projet TEDIJO3. (Image 19/19)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Atelier de lancement TEDIJO3"
  },

  // Action 2: Programme RESPECT (extracted from 8 Mars images naming set 2)
  {
    "id": 63,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 1",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/7.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 1/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 64,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 2",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/17.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 2/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 65,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 3",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/21.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 3/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 66,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 4",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/22.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 4/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 67,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 5",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/26.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 5/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 68,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 6",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/27.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 6/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 69,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 7",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/31.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 7/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 70,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 8",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/32.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 8/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 71,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 9",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/34.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 9/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 72,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 10",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/40.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 10/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },
  {
    "id": 73,
    "title": "Programme RESPECT - Sensibilisation et Plaidoyer - Vue 11",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/42.webp",
    "desc": "Photo prise lors des activités de sensibilisation du Programme RESPECT. (Image 11/11)",
    "date": "2025/2026",
    "tag": "DSSR & VBG",
    "section": "Programme RESPECT"
  },

  // Action 3: 8 Mars
  {
    "id": 54,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 1",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1150.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 1/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 55,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 2",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1158.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 2/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 56,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 3",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1198.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 3/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 57,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 4",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1217.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 4/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 58,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 5",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1248.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 5/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 59,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 6",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1260.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 6/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 60,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 7",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_9311.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 7/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 61,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 8",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_9318.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 8/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 62,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 9",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_9339.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 9/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 74,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 10",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1356.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 10/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 75,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 11",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1360.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 11/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 76,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 12",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1361.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 12/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 77,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 13",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1364.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 13/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 78,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 14",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1373.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 14/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 79,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 15",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1471.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 15/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 80,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 16",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1496.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 16/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 81,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 17",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1503.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 17/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },
  {
    "id": 82,
    "title": "8 Mars - Autonomiser et défendre les droits des femmes - Vue 18",
    "category": "dssr",
    "categoryLabel": "DSSR et VBG",
    "img": "/optimized/gallery/large/IMG_1504.webp",
    "desc": "Photo prise lors de l'activité: 8 Mars - Autonomiser et défendre les droits des femmes. (Image 18/18)",
    "date": "2025/2026",
    "tag": "Droits des femmes",
    "section": "Célébration du 8 Mars"
  },

  // PROJECT 2: Paix et Cohésion Sociale (3 ACTIONS)

  // Action 1: Déjeuner de cohésion sociale
  {
    "id": 1,
    "title": "Déjeuner de cohésion sociale - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484528667_1076017081234581_5468232618266679322_n.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 1/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 2,
    "title": "Déjeuner de cohésion sociale - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484555152_1076017031234586_8611261274879065372_n.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 2/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 3,
    "title": "Déjeuner de cohésion sociale - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484783623_1076016857901270_2225617598526822804_n.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 3/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 4,
    "title": "Déjeuner de cohésion sociale - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484072428_1076016864567936_3711715331058270339_n_Hke9aN0.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 4/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 5,
    "title": "Déjeuner de cohésion sociale - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484091679_1076017064567916_7152508016239654659_n_zvV9l6N.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 5/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 6,
    "title": "Déjeuner de cohésion sociale - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484149533_1076016914567931_4185037950618386607_n_p0wZbPv.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 6/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 7,
    "title": "Déjeuner de cohésion sociale - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484164263_1076017021234587_6414870807836586091_n_zCxbPU2.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 7/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 8,
    "title": "Déjeuner de cohésion sociale - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484191805_1076017091234580_1437664556009335235_n_XBjkrLD.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 8/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 9,
    "title": "Déjeuner de cohésion sociale - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484244713_1076016861234603_5269455461605233138_n_ElDnkxg.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 9/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 10,
    "title": "Déjeuner de cohésion sociale - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484269729_1076017331234556_6236149164847289170_n_Fh4q1ab.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 10/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 11,
    "title": "Déjeuner de cohésion sociale - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484320679_1076016027901353_4951928410946398074_n_uuidePd.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 11/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 12,
    "title": "Déjeuner de cohésion sociale - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484342673_1076017034567919_3019854611157333233_n_nQYfxjQ.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 12/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 13,
    "title": "Déjeuner de cohésion sociale - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484348678_1076017051234584_137647462155535418_n_kN23w0y.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 13/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 14,
    "title": "Déjeuner de cohésion sociale - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484355429_1076017041234585_6011780221015654228_n_0cGgYs9.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 14/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 15,
    "title": "Déjeuner de cohésion sociale - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484491957_1076017087901247_335125118563590463_n_RWiaprX.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 15/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 16,
    "title": "Déjeuner de cohésion sociale - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484493172_1076017024567920_3280376124762105683_n_aSlWX1A.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 16/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 17,
    "title": "Déjeuner de cohésion sociale - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/484526147_1076017037901252_8213786220639388458_n_JRhM68I.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 17/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 18,
    "title": "Déjeuner de cohésion sociale - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/485143467_1076017017901254_1283306627836466384_n.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 18/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },
  {
    "id": 19,
    "title": "Déjeuner de cohésion sociale - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "https://busolaong.com/mediafiles/galerie/WhatsApp_Image_2025-05-14_%C3%A0_00.32.19_7533ab1e.jpg",
    "desc": "Photo prise lors de l'activité: Déjeuner de cohésion sociale. (Image 19/19)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de cohésion sociale"
  },

  // Action 2: Déjeuner de plaidoyer
  {
    "id": 83,
    "title": "Déjeuner de plaidoyer - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0325.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 84,
    "title": "Déjeuner de plaidoyer - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0341.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 85,
    "title": "Déjeuner de plaidoyer - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0351.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 86,
    "title": "Déjeuner de plaidoyer - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0357.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 87,
    "title": "Déjeuner de plaidoyer - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0373.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 88,
    "title": "Déjeuner de plaidoyer - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0389.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 89,
    "title": "Déjeuner de plaidoyer - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0400.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 90,
    "title": "Déjeuner de plaidoyer - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0479.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 91,
    "title": "Déjeuner de plaidoyer - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0481.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 92,
    "title": "Déjeuner de plaidoyer - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0666.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 93,
    "title": "Déjeuner de plaidoyer - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0667.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 94,
    "title": "Déjeuner de plaidoyer - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0668.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 95,
    "title": "Déjeuner de plaidoyer - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0675.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 96,
    "title": "Déjeuner de plaidoyer - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0699.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 97,
    "title": "Déjeuner de plaidoyer - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0701.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 98,
    "title": "Déjeuner de plaidoyer - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0703.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 99,
    "title": "Déjeuner de plaidoyer - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0720.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 100,
    "title": "Déjeuner de plaidoyer - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0721.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 101,
    "title": "Déjeuner de plaidoyer - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0723.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 102,
    "title": "Déjeuner de plaidoyer - Vue 20",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0724.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 103,
    "title": "Déjeuner de plaidoyer - Vue 21",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0730.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 104,
    "title": "Déjeuner de plaidoyer - Vue 22",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0734.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },
  {
    "id": 105,
    "title": "Déjeuner de plaidoyer - Vue 23",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG_0735.webp",
    "desc": "Photo prise lors de l'activité: Déjeuner de plaidoyer. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Déjeuner de plaidoyer"
  },

  // Action 3: Bootcamp Immersif
  {
    "id": 106,
    "title": "Bootcamp Immersif - YES 2025 - Vue 1",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250923-WA0043.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 107,
    "title": "Bootcamp Immersif - YES 2025 - Vue 2",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250923-WA0044.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 108,
    "title": "Bootcamp Immersif - YES 2025 - Vue 3",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250923-WA0045.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 109,
    "title": "Bootcamp Immersif - YES 2025 - Vue 4",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250923-WA0046.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 110,
    "title": "Bootcamp Immersif - YES 2025 - Vue 5",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0003.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 111,
    "title": "Bootcamp Immersif - YES 2025 - Vue 6",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0004.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 112,
    "title": "Bootcamp Immersif - YES 2025 - Vue 7",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0005.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 113,
    "title": "Bootcamp Immersif - YES 2025 - Vue 8",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0006.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 114,
    "title": "Bootcamp Immersif - YES 2025 - Vue 9",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0008.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 115,
    "title": "Bootcamp Immersif - YES 2025 - Vue 10",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0009.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 116,
    "title": "Bootcamp Immersif - YES 2025 - Vue 11",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0010.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 117,
    "title": "Bootcamp Immersif - YES 2025 - Vue 12",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0011.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 118,
    "title": "Bootcamp Immersif - YES 2025 - Vue 13",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0012.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 119,
    "title": "Bootcamp Immersif - YES 2025 - Vue 14",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0013.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 120,
    "title": "Bootcamp Immersif - YES 2025 - Vue 15",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0014.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 121,
    "title": "Bootcamp Immersif - YES 2025 - Vue 16",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0015.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 122,
    "title": "Bootcamp Immersif - YES 2025 - Vue 17",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0016.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 123,
    "title": "Bootcamp Immersif - YES 2025 - Vue 18",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0017.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 124,
    "title": "Bootcamp Immersif - YES 2025 - Vue 19",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0018.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 125,
    "title": "Bootcamp Immersif - YES 2025 - Vue 20",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0019.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 126,
    "title": "Bootcamp Immersif - YES 2025 - Vue 21",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0020.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 127,
    "title": "Bootcamp Immersif - YES 2025 - Vue 22",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0022.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },
  {
    "id": 128,
    "title": "Bootcamp Immersif - YES 2025 - Vue 23",
    "category": "paix",
    "categoryLabel": "Paix et Cohésion Sociale",
    "img": "/optimized/gallery/large/IMG-20250926-WA0023.webp",
    "desc": "Photo prise lors de l'activité: Bootcamp Immersif - YES 2025. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Jeunesse",
    "section": "Bootcamp Immersif YES"
  },

  // PROJECT 3: Leadership et Autonomisation (2 ACTIONS)

  // Action 1: 5 ans d'engagement et d'Impact
  {
    "id": 39,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 1",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0165.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 1/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 40,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 2",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0167.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 2/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 41,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 3",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0168.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 3/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 42,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 4",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0175.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 4/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 43,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 5",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0178.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 5/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 44,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 6",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0179.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 6/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 45,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 7",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0181.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 7/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 46,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 8",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0182.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 8/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 47,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 9",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0184.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 9/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 48,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 10",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0185.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 10/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 49,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 11",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0188.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 11/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 50,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 12",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0200.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 12/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 51,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 13",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0211.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 13/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 52,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 14",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0264.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 14/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },
  {
    "id": 53,
    "title": "5 ans d&#x27;engagement et d&#x27;Impact - Vue 15",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/IMG-20250322-WA0268.webp",
    "desc": "Photo prise lors de l'activité: 5 ans d&#x27;engagement et d&#x27;Impact. (Image 15/15)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "5 ans d'engagement et d'Impact"
  },

  // Action 2: Cérémonie de présentation des voeux
  {
    "id": 129,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 1",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_30.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 1/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 130,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 2",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_27.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 2/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 131,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 3",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_28.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 3/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 132,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 4",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_11.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 4/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 133,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 5",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_38.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 5/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 134,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 6",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_39.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 6/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 135,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 7",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_42.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 7/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 136,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 8",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_49.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 8/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 137,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 9",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_46.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 9/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 138,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 10",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_14.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 10/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 139,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 11",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_17.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 11/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 140,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 12",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_26.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 12/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 141,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 13",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_37.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 13/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 142,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 14",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_32.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 14/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 143,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 15",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_48.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 15/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 144,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 16",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_21.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 16/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 145,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 17",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_31.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 17/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 146,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 18",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_51.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 18/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 147,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 19",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_5.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 19/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 148,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 20",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_13.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 20/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 149,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 21",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_73.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 21/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 150,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 22",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_25.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 22/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  },
  {
    "id": 151,
    "title": "Cérémonie de présentation des voeux au CA et aux PTF de Busola - Vue 23",
    "category": "leadership",
    "categoryLabel": "Leadership et Autonomisation",
    "img": "/optimized/gallery/large/BUSOLA_36.jpg.webp",
    "desc": "Photo prise lors de l'activité: Cérémonie de présentation des voeux au CA et aux PTF de Busola. (Image 23/23)",
    "date": "2025/2026",
    "tag": "Vie de l'ONG",
    "section": "Cérémonie de présentation des voeux"
  }
];
